# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tidevec_pb2 as tidevec__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tidevec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TideVecStub:
    """================================================================
    TideVec gRPC Service — single source of truth for all SDKs
    Compiled to: C++ / Python / Go / Java
    ================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/tidevec.v1.TideVec/CreateCollection',
                request_serializer=tidevec__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=tidevec__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.DropCollection = channel.unary_unary(
                '/tidevec.v1.TideVec/DropCollection',
                request_serializer=tidevec__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=tidevec__pb2.DropCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollection = channel.unary_unary(
                '/tidevec.v1.TideVec/GetCollection',
                request_serializer=tidevec__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=tidevec__pb2.GetCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/tidevec.v1.TideVec/ListCollections',
                request_serializer=tidevec__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=tidevec__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.UpdateTemporal = channel.unary_unary(
                '/tidevec.v1.TideVec/UpdateTemporal',
                request_serializer=tidevec__pb2.UpdateTemporalRequest.SerializeToString,
                response_deserializer=tidevec__pb2.UpdateTemporalResponse.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/tidevec.v1.TideVec/Upsert',
                request_serializer=tidevec__pb2.UpsertRequest.SerializeToString,
                response_deserializer=tidevec__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/tidevec.v1.TideVec/Delete',
                request_serializer=tidevec__pb2.DeleteRequest.SerializeToString,
                response_deserializer=tidevec__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.BatchUpsert = channel.stream_unary(
                '/tidevec.v1.TideVec/BatchUpsert',
                request_serializer=tidevec__pb2.UpsertRequest.SerializeToString,
                response_deserializer=tidevec__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/tidevec.v1.TideVec/Search',
                request_serializer=tidevec__pb2.SearchRequest.SerializeToString,
                response_deserializer=tidevec__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.BatchSearch = channel.unary_unary(
                '/tidevec.v1.TideVec/BatchSearch',
                request_serializer=tidevec__pb2.BatchSearchRequest.SerializeToString,
                response_deserializer=tidevec__pb2.BatchSearchResponse.FromString,
                _registered_method=True)
        self.SearchStream = channel.unary_stream(
                '/tidevec.v1.TideVec/SearchStream',
                request_serializer=tidevec__pb2.SearchRequest.SerializeToString,
                response_deserializer=tidevec__pb2.SearchResult.FromString,
                _registered_method=True)
        self.AddEdges = channel.unary_unary(
                '/tidevec.v1.TideVec/AddEdges',
                request_serializer=tidevec__pb2.AddEdgesRequest.SerializeToString,
                response_deserializer=tidevec__pb2.AddEdgesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/tidevec.v1.TideVec/Health',
                request_serializer=tidevec__pb2.HealthRequest.SerializeToString,
                response_deserializer=tidevec__pb2.HealthResponse.FromString,
                _registered_method=True)


class TideVecServicer:
    """================================================================
    TideVec gRPC Service — single source of truth for all SDKs
    Compiled to: C++ / Python / Go / Java
    ================================================================

    """

    def CreateCollection(self, request, context):
        """---- Collections ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTemporal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """---- Vectors ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpsert(self, request_iterator, context):
        """client streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """---- Search ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStream(self, request, context):
        """server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdges(self, request, context):
        """---- Graph ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """---- Health ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TideVecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=tidevec__pb2.CreateCollectionRequest.FromString,
                    response_serializer=tidevec__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=tidevec__pb2.DropCollectionRequest.FromString,
                    response_serializer=tidevec__pb2.DropCollectionResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=tidevec__pb2.GetCollectionRequest.FromString,
                    response_serializer=tidevec__pb2.GetCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=tidevec__pb2.ListCollectionsRequest.FromString,
                    response_serializer=tidevec__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'UpdateTemporal': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTemporal,
                    request_deserializer=tidevec__pb2.UpdateTemporalRequest.FromString,
                    response_serializer=tidevec__pb2.UpdateTemporalResponse.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=tidevec__pb2.UpsertRequest.FromString,
                    response_serializer=tidevec__pb2.UpsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=tidevec__pb2.DeleteRequest.FromString,
                    response_serializer=tidevec__pb2.DeleteResponse.SerializeToString,
            ),
            'BatchUpsert': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchUpsert,
                    request_deserializer=tidevec__pb2.UpsertRequest.FromString,
                    response_serializer=tidevec__pb2.UpsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=tidevec__pb2.SearchRequest.FromString,
                    response_serializer=tidevec__pb2.SearchResponse.SerializeToString,
            ),
            'BatchSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSearch,
                    request_deserializer=tidevec__pb2.BatchSearchRequest.FromString,
                    response_serializer=tidevec__pb2.BatchSearchResponse.SerializeToString,
            ),
            'SearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchStream,
                    request_deserializer=tidevec__pb2.SearchRequest.FromString,
                    response_serializer=tidevec__pb2.SearchResult.SerializeToString,
            ),
            'AddEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdges,
                    request_deserializer=tidevec__pb2.AddEdgesRequest.FromString,
                    response_serializer=tidevec__pb2.AddEdgesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=tidevec__pb2.HealthRequest.FromString,
                    response_serializer=tidevec__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tidevec.v1.TideVec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tidevec.v1.TideVec', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TideVec:
    """================================================================
    TideVec gRPC Service — single source of truth for all SDKs
    Compiled to: C++ / Python / Go / Java
    ================================================================

    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/CreateCollection',
            tidevec__pb2.CreateCollectionRequest.SerializeToString,
            tidevec__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/DropCollection',
            tidevec__pb2.DropCollectionRequest.SerializeToString,
            tidevec__pb2.DropCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/GetCollection',
            tidevec__pb2.GetCollectionRequest.SerializeToString,
            tidevec__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/ListCollections',
            tidevec__pb2.ListCollectionsRequest.SerializeToString,
            tidevec__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTemporal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/UpdateTemporal',
            tidevec__pb2.UpdateTemporalRequest.SerializeToString,
            tidevec__pb2.UpdateTemporalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/Upsert',
            tidevec__pb2.UpsertRequest.SerializeToString,
            tidevec__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/Delete',
            tidevec__pb2.DeleteRequest.SerializeToString,
            tidevec__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/tidevec.v1.TideVec/BatchUpsert',
            tidevec__pb2.UpsertRequest.SerializeToString,
            tidevec__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/Search',
            tidevec__pb2.SearchRequest.SerializeToString,
            tidevec__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/BatchSearch',
            tidevec__pb2.BatchSearchRequest.SerializeToString,
            tidevec__pb2.BatchSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tidevec.v1.TideVec/SearchStream',
            tidevec__pb2.SearchRequest.SerializeToString,
            tidevec__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/AddEdges',
            tidevec__pb2.AddEdgesRequest.SerializeToString,
            tidevec__pb2.AddEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tidevec.v1.TideVec/Health',
            tidevec__pb2.HealthRequest.SerializeToString,
            tidevec__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
