global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tidevec
    static_configs:
      - targets: ['tidevec:6399']
    metrics_path: /metrics

  - job_name: tidevec-gpu
    static_configs:
      - targets: ['tidevec-gpu:6399']
    metrics_path: /metrics
